version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ec2-user
    - location: scripts/before_install.sh
      timeout: 300
      runas: ec2-user
  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 300
      runas: ec2-user 
