version: 0.2

phases:
  install:
    commands:
     -sudo su
     -yum update -y
     -yum install httpd -y
     -service httpd start
     -chkconfig httpd on
  build:
    commands:
    - echo "This is build phase... Zipping my webpage"
 
  post_build:
    commands:
    - echo "Deployed to EC2"
artifacts:
  files:
    - '**/*'
