version: 0.2

phases:
 #  commands:
     -dnf update -y
     -dnf install httpd -y
     -service httpd start
     -chkconfig httpd on
  build:
    commands:
    - echo "This is build phase... Zipping my webpage"
 
  post_build:
    commands:
    - echo "Deployed to EC2"
artifacts:
  files:
    - '**/*'
